# Generated by Django 5.1.4 on 2025-06-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_is_active_remove_employee_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='Monthly_salary',
        ),
    ]
