# Generated by Django 5.1.4 on 2025-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_options_alter_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['created_at'], name='employees_e_created_52c8e7_idx'),
        ),
    ]
