# Generated by Django 5.1.4 on 2025-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_employees_e_created_52c8e7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Junior Designer', 'Junior Designer'), ('Designer', 'Designer'), ('Senior Designer', 'Senior Designer'), ('Junior Developer', 'Junior Developer'), ('Developer', 'Developer'), ('Senior Developer', 'Senior Developer'), ('Tester', 'Tester'), ('QA Engineer', 'QA Engineer'), ('Junior Manager', 'Junior Manager'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('Monthly_salary__gte', 0)), name='non_negative_salary'),
        ),
    ]
