# Generated by Django 4.2 on 2025-04-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
