# Generated by Django 4.2.8 on 2025-04-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
