# Generated by Django 5.1.7 on 2025-04-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
