# Generated by Django 5.1.7 on 2025-04-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_image',
            field=models.ImageField(default=1, upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
