# Generated by Django 4.2 on 2025-04-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
