# Generated by Django 4.2 on 2025-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_recipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
