# Generated by Django 4.2 on 2025-04-24 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'permissions': [('can_add_recipe', 'Can add recipes through web interface'), ('can_edit_recipe', 'Can edit existing recipes'), ('can_delete_recipe', 'Can delete recipes')], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_description',
            field=models.TextField(help_text='Detailed recipe description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_image',
            field=models.ImageField(help_text='Upload recipe image (JPEG or PNG)', upload_to='recipes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
