# Generated by Django 4.2.8 on 2025-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_recipe_options_alter_recipe_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
