# Generated by Django 4.2.8 on 2025-04-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_category_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
