# Generated by Django 4.2.8 on 2025-04-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vege.category'),
        ),
    ]
